-- Monitor IA · Supabase
-- Armazena snapshots dos relatórios R72/R74 coletados manualmente pelo Monitor.
-- O navegador nunca acessa estas tabelas diretamente.

create table if not exists public.report_snapshots (
  id bigint generated by default as identity primary key,
  report_id smallint not null check (report_id in (72, 74)),
  period_start date not null,
  period_end date not null,
  collected_at timestamptz not null default now(),
  rows jsonb not null default '[]'::jsonb,
  rows_count integer not null default 0,
  source text not null default 'manual'
);

create index if not exists report_snapshots_period_idx
  on public.report_snapshots (period_start, period_end, report_id, collected_at desc);

create index if not exists report_snapshots_collected_idx
  on public.report_snapshots (collected_at desc);

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  success boolean not null default false,
  period_start date,
  period_end date,
  r72_rows integer not null default 0,
  r74_rows integer not null default 0,
  error text
);

create index if not exists sync_runs_started_idx
  on public.sync_runs (started_at desc);

alter table public.report_snapshots enable row level security;
alter table public.sync_runs enable row level security;

revoke all on table public.report_snapshots from anon, authenticated;
revoke all on table public.sync_runs from anon, authenticated;

grant all on table public.report_snapshots to service_role;
grant all on table public.sync_runs to service_role;

create or replace function public.monitor_ia_cleanup(days_to_keep integer default 365)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.report_snapshots
  where collected_at < now() - make_interval(days => greatest(days_to_keep, 1));

  delete from public.sync_runs
  where started_at < now() - make_interval(days => greatest(days_to_keep, 1));
$$;

revoke all on function public.monitor_ia_cleanup(integer) from public;
grant execute on function public.monitor_ia_cleanup(integer) to service_role;
