'use strict';
var $=function(id){return document.getElementById(id)},esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]})},norm=function(v){return String(v==null?'':v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()},pct=function(a,b){return b?Math.round(a/b*100):0},fmt=function(v){return Number(v||0).toLocaleString('pt-BR')};
function ymdLocal(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function dates(p){var d=new Date(),s=new Date(d),e=new Date(d);if(p==='yesterday'){s.setDate(d.getDate()-1);e.setDate(d.getDate()-1)}else if(p==='7days')s.setDate(d.getDate()-6);return[ymdLocal(s),ymdLocal(e)]}
function csvRows(raw){if(Array.isArray(raw))return raw;var t=raw&&raw.data!=null?raw.data:raw||'';if(typeof t==='object')return Array.isArray(t.rows)?t.rows:Array.isArray(t.data)?t.data:[];t=String(t).replace(/^\uFEFF/,'').trim();if(!t)return[];var lines=t.split(/\r?\n/).filter(Boolean),delim=[';','\t','|',','].sort(function(a,b){return lines[0].split(b).length-lines[0].split(a).length})[0];function split(s){var a=[],c='',q=false;for(var i=0;i<s.length;i++){var ch=s[i];if(ch==='"'){if(q&&s[i+1]==='"'){c+='"';i++}else q=!q}else if(ch===delim&&!q){a.push(c.trim());c=''}else c+=ch}a.push(c.trim());return a}var h=split(lines[0]);return lines.slice(1).map(function(l){var v=split(l),o={};h.forEach(function(k,i){o[k||('c'+i)]=v[i]||''});return o})}
function col(o,n){var k=Object.keys(o||{});return k.find(function(x){return n.some(function(y){return norm(x).indexOf(norm(y))>=0})})||''}
var help=['Resposta clara','Passo a passo útil','Fácil de entender','Atendimento ágil','Entendeu meu pedido','Não resolveu','Resposta incorreta','Resposta confusa','Passo a passo longo','Precisei repetir'],pos=new Set(help.slice(0,5).map(norm)),neg=new Set(help.slice(5).map(norm));
var bot=[['Atendimento retomado - IA - SPC','SPC'],['Atendimento retomado - IA - Safe','Safe'],['Falha de conhecimento - IA - SPC','SPC'],['Falha de conhecimento - IA - Safe','Safe'],['Finaliza SafeNota - IA - Safe','Safe'],['Inatividade - Finalizado - IA - SPC','SPC'],['Inatividade - Finalizado - IA - Safe','Safe'],['Iniciado atendimento - IA - SPC','SPC'],['Iniciado atendimento - IA - Safe','Safe'],['Não retomou atendimento - IA - SPC','SPC'],['Não retomou atendimento - IA - Safe','Safe'],['Pesquisa encaminhada - Possível solução - IA - SPC','SPC'],['Pesquisa encaminhada - Possível solução - IA - Safe','Safe'],['Problema não resolvido - IA - SPC','SPC'],['Problema não resolvido - IA - Safe','Safe'],['Problema resolvido - IA - SPC','SPC'],['Problema resolvido - IA - Safe','Safe'],['Retomada após inatividade - IA - Safe','Safe'],['Transfere AC - IA - Safe','Safe'],['Transfere Documental - IA - Safe','Safe'],['Transferencial Comercial - IA - Safe','Safe'],['Transferência fila - IA - SPC','SPC'],['Transferência fila - IA - Safe','Safe']];
function classify(v){var x=norm(v);if(x.indexOf('problema nao resolvido')>=0)return'nao';if(x.indexOf('falha de conhecimento')>=0)return'outro';if(x.indexOf('problema resolvido')>=0)return'resolvido';if(x.indexOf('finaliza safenota')>=0)return'outro';if(x.indexOf('transferencia fila')>=0||x.indexOf('transfere ac')>=0||x.indexOf('transferencia ac')>=0||x.indexOf('transfere documental')>=0||x.indexOf('transferencia documental')>=0||x.indexOf('transferencial comercial')>=0||x.indexOf('transferencia comercial')>=0||x.indexOf('transfere comercial')>=0)return'transferido';if(x.indexOf('nao retomou')>=0||x.indexOf('nao retornou')>=0)return'outro';if(x.indexOf('atendimento retomado')>=0||x.indexOf('retomada apos inatividade')>=0||x.indexOf('retomado')>=0||x.indexOf('retomou atendimento')>=0)return'retomado';if(x.indexOf('inatividade')>=0)return'inatividade';if(x.indexOf('pesquisa encaminhada')>=0)return'possivel';if(x.indexOf('iniciado atendimento')>=0)return'outro';return'outro'}
function agent(v,p){var x=norm(v),s=String(v||'').trim(),bp=norm(p),code=function(a){return new RegExp('(^|[^\\d/:.,])('+a.join('|')+')([^\\d/:.,]|$)').test(s)},word=function(w){return new RegExp('(^|[^a-z0-9])'+w+'([^a-z0-9]|$)').test(x)};if(code(['292929'])||x.indexOf('transferencia manual')>=0)return'Transferência manual';if(code(['3002','323232'])||word('spc aci')||word('aci'))return'SPC ACI';if(code(['3001','313131'])||word('spc age')||word('age'))return'SPC AGE';if(code(['3000','393939'])||word('spc'))return'IA SPC';if(code(['10','66666'])||x.indexOf('safira')>=0)return'Assistente Safira';if(code(['676767'])||word('cliente inativo')||x.indexOf('retomar atendimento')>=0)return'Cliente inativo / Retomar atendimento - IA';if(!s){var m=bp.match(/(?:^|\\D)(5[2-9]|6[0-9]|7[0-4])(?:\\D|$)/);if(m){var pointIndex=Number(m[1])-52;if(bot[pointIndex])return bot[pointIndex][1]==='Safe'?'Assistente Safira':'IA SPC'}if(bp.indexOf('ia - safe')>=0||bp.indexOf('ia safe')>=0||bp.indexOf('safenota')>=0||bp.indexOf(' safe')>=0)return'Assistente Safira';if(bp.indexOf('ia - spc')>=0||bp.indexOf('ia spc')>=0||bp.indexOf(' spc')>=0)return'IA SPC'}return s.length>32?s.slice(0,30)+'…':s||'Sem IA identificada'}
function dt(v){var s=String(v||''),m=s.match(/(\d{1,2})\/(\d{1,2})\/(\d{4})(?:\D{1,4}(\d{1,2}):(\d{2})(?::(\d{2}))?)?/);if(m)return new Date(+m[3],+m[2]-1,+m[1],+(m[4]||0),+(m[5]||0),+(m[6]||0)).getTime();m=s.match(/(\d{4})-(\d{2})-(\d{2})(?:[ T](\d{2}):(\d{2})(?::(\d{2}))?)?/);return m?new Date(+m[1],+m[2]-1,+m[3],+(m[4]||0),+(m[5]||0),+(m[6]||0)).getTime():0}
function analyze72(raw){var rows=csvRows(raw),s=rows[0]||{},cp=col(s,['pontos de bot','bot point','ponto de bot']),pr=col(s,['protocolo']),ag=col(s,['agente','agent']),da=col(s,['data/hora','data hora','data']),co=col(s,['telefone','contato','contact','phone']),map={};rows.forEach(function(r){var p=String(r[pr]||'').trim(),point=String(r[cp]||'').trim();if(!p)return;var eventOutcome=classify(point),isProblemUnresolved=eventOutcome==='nao';var x=map[p]||(map[p]={protocol:p,agent:agent(r[ag],point),contact:String(r[co]||''),events:[],hasProblemUnresolved:false,unresolvedPoint:'',unresolvedDate:''});if(x.agent==='Sem IA identificada')x.agent=agent(r[ag],point);if(isProblemUnresolved){x.hasProblemUnresolved=true;x.unresolvedPoint=point;x.unresolvedDate=String(r[da]||'')}x.events.push({point:point,out:eventOutcome,date:String(r[da]||'')})});var ps=Object.keys(map).map(function(k){var x=map[k],priority={nao:6,resolvido:5,transferido:4,possivel:3,inatividade:2};x.events.forEach(function(e,i){e.index=i;e.ms=dt(e.date)});var rel=x.events.filter(function(e){return ['resolvido','transferido','nao','inatividade','possivel'].indexOf(e.out)>=0});rel.sort(function(a,b){if(a.ms&&b.ms&&a.ms!==b.ms)return a.ms-b.ms;if(a.index!==b.index)return a.index-b.index;return(priority[a.out]||0)-(priority[b.out]||0)});x.outcome=rel.length?rel[rel.length-1].out:'outro';x.firstDate=x.events[0]?x.events[0].date:'';x.lastDate=x.events[x.events.length-1]?x.events[x.events.length-1].date:'';x.finalPoint=rel.length?rel[rel.length-1].point:(x.events[x.events.length-1]?x.events[x.events.length-1].point:'');return x});return{rows:rows,protocols:ps}}
function kind(q,v){var x=norm(v),qn=norm(q);if(pos.has(x)||neg.has(x))return'help';var n=Number(String(v).replace(',','.'));if(n>=1&&n<=5&&/nota|avalia|satisf|estrela|1 a 5/.test(qn))return'note';if(/ajud|auxili|contribu|motivo/.test(qn))return'help';if(/coment|sugest|observa|elogio|critica|mensagem|porque|por que/.test(qn))return'comment';return'other'}
function analyze74(raw){var rows=csvRows(raw),s=rows[0]||{},pr=col(s,['protocolo','protocol']),ag=col(s,['agente','agent']),qu=col(s,['questao','pergunta','question']),re=col(s,['resposta','answer','response','nota']),da=col(s,['data/hora','data hora','data','date']),map={};rows.forEach(function(r){var p=String(r[pr]||'').trim();if(!p)return;var x=map[p]||(map[p]={protocol:p,agent:agent(r[ag]),note:0,help:[],comment:'',other:[],date:String(r[da]||'')});var v=String(r[re]||'').trim(),k=kind(r[qu],v);if(k==='note'){var n=Number(v.replace(',','.'));if(n>=1&&n<=5)x.note=n}else if(k==='help'){v.split(/[,;|\n]+/).map(function(z){return z.trim()}).filter(Boolean).forEach(function(z){var h=help.find(function(a){return norm(a)===norm(z)});if(h&&!x.help.includes(h))x.help.push(h)});if(!x.help.length&&v)x.help.push(v)}else if(k==='comment'&&v)x.comment=v;else if(v)x.other.push({q:String(r[qu]||''),a:v})});return Object.keys(map).map(function(k){return map[k]})}
var data=null,mode='cards',sv={q:'',agent:'',option:'',filter:'all',page:1,size:20},uv={q:'',agent:'',filter:'all',outcome:'nao',page:1,size:20};
function k(label,value,sub){var x=norm(label),tone=x.indexOf('não')>=0||x.indexOf('melhorar')>=0?' tone-bad':x.indexOf('transfer')>=0?' tone-blue':x.indexOf('nota')>=0||x.indexOf('satisf')>=0?' tone-good':' tone-info',icon=tone.indexOf('bad')>=0?'!':tone.indexOf('good')>=0?'☆':tone.indexOf('blue')>=0?'↔':'✓';return'<div class="kpi'+tone+'"><div class="kpi-icon">'+icon+'</div><div class="kpi-body"><div class="kpi-label">'+esc(label)+'</div><div class="kpi-value">'+esc(value)+'</div>'+(sub?'<div class="kpi-sub">'+esc(sub)+'</div>':'')+'</div></div>'}
function positiveCount(s){return s.filter(function(x){return x.note>=4}).length}function nPositive(s){var n=s.filter(function(x){return x.note});return n.length?pct(positiveCount(n),n.length):0}function renderOverview(){var p=data.r72.protocols.filter(function(x){return DESFECHOS.indexOf(x.outcome)>=0}),s=data.r74,total=p.length,res=p.filter(function(x){return x.outcome==='resolvido'}).length,tr=p.filter(function(x){return x.outcome==='transferido'}).length,un=(function(){var rows=data.r72.rows||[],h=rows[0]||{},cp=col(h,['pontos de bot','bot point','checkpoint','ponto de bot']),pr=col(h,['protocolo']),seen={};rows.forEach(function(r){var p=String(r[pr]||'').trim(),point=norm(String(r[cp]||'')).replace(/\s+/g,' ');if(p&&point.indexOf('problema nao resolvido')>=0)seen[p]=1});return Object.keys(seen).length})(),ns=s.filter(function(x){return x.note}),avg=ns.length?ns.reduce(function(a,x){return a+x.note},0)/ns.length:0;$('overviewKpis').innerHTML=k('Resolvidos pela IA',pct(res,total)+'%',fmt(res)+' de '+fmt(total)+' atendimentos')+k('Transferidos',pct(tr,total)+'%',fmt(tr)+' encaminhados para humano')+k('Nota média',ns.length?avg.toFixed(2).replace('.',','):'—',ns.length+' avaliações')+k('Satisfação positiva',nPositive(s)+'%',positiveCount(s)+' notas 4 ou 5');var ds=[['resolvido','Resolvidos pela IA'],['transferido','Transferidos'],['nao','Não resolvidos'],['inatividade','Inatividade'],['possivel','Aguardando confirmação'],['retomado','Retomados']];$('outcomes').innerHTML=ds.map(function(d){var q=d[0]==='nao'?un:p.filter(function(x){return x.outcome===d[0]}).length;return'<div class="r"><b>'+d[1]+'</b><span>'+fmt(q)+'</span><div class="bar"><i style="width:'+pct(q,total)+'%"></i></div><small>'+pct(q,total)+'%</small></div>'}).join('');$('outcomeBadge').textContent=fmt(total)+' protocolos';renderAgents()}
function renderAgents(){var a={};data.r72.protocols.filter(function(x){return DESFECHOS.indexOf(x.outcome)>=0}).forEach(function(x){a[x.agent]||(a[x.agent]={t:0,r:0,tr:0,u:0,n:[]});a[x.agent].t++;if(x.outcome==='resolvido')a[x.agent].r++;if(x.outcome==='transferido')a[x.agent].tr++;if(isUnresolvedProtocol(x))a[x.agent].u++;if(x.survey&&x.survey.note)a[x.agent].n.push(x.survey.note)});var arr=Object.keys(a).sort(function(x,y){return a[y].t-a[x].t});if(mode==='cards'){$('agentCards').hidden=false;$('agentTable').hidden=true;$('agentCards').innerHTML=arr.map(function(name){var x=a[name],av=x.n.length?x.n.reduce(function(q,v){return q+v},0)/x.n.length:0;return'<div class="agent"><b>'+esc(name)+'</b><small>'+fmt(x.t)+' protocolos</small><div><span><strong>'+x.r+'</strong> resolvidos</span><span><strong>'+x.tr+'</strong> transferidos</span><span><strong>'+x.u+'</strong> não resolvidos</span><span><strong>'+(x.n.length?av.toFixed(2).replace('.',','):'—')+'</strong> nota</span></div></div>'}).join('')||'<div class="empty">Nenhuma IA encontrada.</div>'}else{$('agentCards').hidden=true;$('agentTable').hidden=false;$('agentTable').innerHTML='<table><tr><th>IA</th><th>Protocolos</th><th>Resolvidos</th><th>Transferidos</th><th>Não resolvidos</th><th>Nota</th></tr>'+arr.map(function(name){var x=a[name],av=x.n.length?x.n.reduce(function(q,v){return q+v},0)/x.n.length:0;return'<tr><td>'+esc(name)+'</td><td>'+x.t+'</td><td>'+x.r+'</td><td>'+x.tr+'</td><td>'+x.u+'</td><td>'+(x.n.length?av.toFixed(2).replace('.',','):'—')+'</td></tr>'}).join('')+'</table>'}}
function surveyFiltered(){return data.r74.filter(function(x){var z=norm([x.protocol,x.agent,x.comment,x.help.join(' '),x.other.map(function(o){return o.a}).join(' ')].join(' '));return(!sv.q||z.indexOf(norm(sv.q))>=0)&&(!sv.agent||x.agent===sv.agent)&&(!sv.option||x.help.indexOf(sv.option)>=0)&&(sv.filter==='all'||sv.filter==='high'&&x.note>=4||sv.filter==='low'&&x.note&&x.note<=3||sv.filter==='comment'&&x.comment)})}
function renderSurveys(){var s=data.r74,n=s.filter(function(x){return x.note}),avg=n.length?n.reduce(function(a,x){return a+x.note},0)/n.length:0;$('surveyKpis').innerHTML=k('Pesquisas respondidas',fmt(s.length))+k('Nota média',n.length?avg.toFixed(2).replace('.',','):'—')+k('Satisfação positiva',fmt(n.filter(function(x){return x.note>=4}).length))+k('Pontos a melhorar',fmt(n.filter(function(x){return x.note<=3}).length))+k('Com comentário',fmt(s.filter(function(x){return x.comment}).length));$('scoreLabel').textContent=n.length?avg.toFixed(2).replace('.',','):'—';$('satDist').innerHTML=[1,2,3,4,5].map(function(v){var q=n.filter(function(x){return x.note===v}).length;return'<div class="r mini"><b>'+v+'</b><div class="bar"><i style="width:'+pct(q,n.length)+'%"></i></div><span>'+q+'</span></div>'}).join('');var hc={};s.forEach(function(x){x.help.forEach(function(h){hc[h]=(hc[h]||0)+1})});$('helpBody').innerHTML='<div class="help-columns"><div class="help-box good"><h3>Pontos fortes</h3>'+help.slice(0,5).map(function(h){return'<div class="r mini"><b>'+esc(h)+'</b><div class="bar"><i style="width:'+pct(hc[h]||0,Math.max(1,help.slice(0,5).reduce(function(a,h){return a+(hc[h]||0)},0)))+'%"></i></div><span>'+fmt(hc[h]||0)+'</span></div>'}).join('')+'</div><div class="help-box bad"><h3>Pontos a melhorar</h3>'+help.slice(5).map(function(h){return'<div class="r mini"><b>'+esc(h)+'</b><div class="bar"><i style="width:'+pct(hc[h]||0,Math.max(1,help.slice(5).reduce(function(a,h){return a+(hc[h]||0)},0)))+'%"></i></div><span>'+fmt(hc[h]||0)+'</span></div>'}).join('')+'</div></div>';$('surveyAgent').innerHTML='<option value="">Todas as IAs</option>'+Array.from(new Set(s.map(function(x){return x.agent}))).sort().map(function(a){return'<option>'+esc(a)+'</option>'}).join('');$('surveyOption').innerHTML='<option value="">Todos os motivos</option>'+help.map(function(h){return'<option>'+esc(h)+'</option>'}).join('');renderSurveyList()}
function renderSurveyList(){var all=surveyFiltered(),pages=Math.max(1,Math.ceil(all.length/sv.size));sv.page=Math.min(sv.page,pages);var rows=all.slice((sv.page-1)*sv.size,sv.page*sv.size);$('surveyCount').textContent=fmt(all.length)+' respostas';$('surveyChips').innerHTML=[['all','Todas'],['high','Notas 4–5'],['low','Notas 1–3'],['comment','Comentários']].map(function(x){return'<button class="chip '+(sv.filter===x[0]?'active':'')+'" data-sfilter="'+x[0]+'">'+x[1]+'</button>'}).join('');$('surveyList').innerHTML=rows.map(function(x){var low=x.note&&x.note<=3;return'<div class="survey-row"><div class="score-box '+(low?'low':'')+'">'+(x.note?x.note:'—')+'<small style="display:block;font-size:6px;font-weight:400">nota</small></div><div class="row-main"><div class="row-top"><b>Protocolo '+esc(x.protocol)+'</b><span class="pill">'+esc(x.agent)+'</span><span class="row-date">'+esc(x.date||'')+'</span></div><div class="row-content">'+(x.help.length?'<strong>Como a IA ajudou</strong> &nbsp; '+x.help.map(function(h){return'<span class="pill">'+esc(h)+'</span>'}).join(' '):'')+(x.comment?'<div style="margin-top:6px"><strong>Comentário</strong> &nbsp; '+esc(x.comment)+'</div>':'')+(x.other.length?'<div style="margin-top:6px"><strong>Outras</strong> &nbsp; '+esc(x.other.map(function(o){return o.a}).join(' · '))+'</div>':'')+'</div></div><button type="button" class="view-btn" data-protocol="'+esc(x.protocol)+'">⌕ &nbsp;Ver conversa</button></div>'}).join('')||'<div class="empty">Nenhuma resposta encontrada.</div>';$('surveyPager').innerHTML=pages>1?'<button data-sp="-1">Anterior</button><span>Página '+sv.page+' de '+pages+'</span><button data-sp="1">Próxima</button>':''}
function isUnresolvedProtocol(x){return x.hasProblemUnresolved===true||x.outcome==='nao'}function unresolvedBase(){return data.r72.protocols.filter(isUnresolvedProtocol)}
/* Lista da aba Protocolos: segue o desfecho escolhido (padrão: não resolvidos) */
/* Desfechos que contam como "com desfecho" (base dos percentuais) */
var DESFECHOS=['resolvido','transferido','nao','inatividade','possivel','finalizado','safenota'];
var OUTCOME_LIST={nao:'Não resolvidos',resolvido:'Resolvidos pela IA',transferido:'Transferidos',inatividade:'Inatividade',possivel:'Aguardando confirmação',finalizado:'Finalizado (não retomou)',safenota:'Finaliza SafeNota',andamento:'Em andamento (até 24h)',falha:'Falha de conhecimento',sem:'Sem desfecho',todos:'Todos com desfecho'};
var OUTCOME_ONE={nao:'Problema não resolvido',resolvido:'Resolvido',transferido:'Transferido',inatividade:'Inatividade',possivel:'Aguardando confirmação',retomado:'Retomado',finalizado:'Finalizado',safenota:'Finaliza SafeNota',andamento:'Em andamento',outro:'Sem desfecho'};
function failurePoint(x){var e=(x.events||[]).filter(function(v){return norm(v.point).indexOf('falha de conhecimento')>=0});return e.length?e[e.length-1]:null}
function hasFailure(x){return!!failurePoint(x)}
/* trilha de bot points do protocolo, sem o sufixo da IA e sem repetições seguidas */
function trail(x){var out=[];(x.events||[]).forEach(function(e){var t=String(e.point||'').replace(/\s*-\s*IA\s*-\s*(SPC|Safe)\s*$/i,'').trim();if(t&&out[out.length-1]!==t)out.push(t)});return out.join(' → ')}
function listBase(){var o=uv.outcome||'nao',all=data.r72.protocols;if(o==='nao')return all.filter(isUnresolvedProtocol);if(o==='falha')return all.filter(hasFailure);if(o==='sem')return all.filter(function(x){return x.outcome==='outro'});if(o==='todos')return all.filter(function(x){returnDESFECHOS.indexOf(x.outcome)>=0});return all.filter(function(x){return x.outcome===o})}
function unresolved(){return listBase().filter(function(x){var z=norm([x.protocol,x.agent,x.contact,x.finalPoint,x.survey&&x.survey.comment,x.survey&&x.survey.help].join(' '));return(!uv.q||z.indexOf(norm(uv.q))>=0)&&(!uv.agent||x.agent===uv.agent)&&(uv.filter==='all'||uv.filter==='note'&&x.survey&&x.survey.note||uv.filter==='comment'&&x.survey&&x.survey.comment||uv.filter==='nohelp'&&x.survey&&x.survey.help.some(function(h){return neg.has(norm(h))}))})}
function renderProtocols(){var p=data.r72.protocols,un=unresolvedBase();var most={};p.forEach(function(x){most[x.agent]=(most[x.agent]||0)+1});var top=Object.keys(most).sort(function(a,b){return most[b]-most[a]})[0]||'—';var low=data.r74.filter(function(x){return x.note&&x.note<=3});var improve={};low.forEach(function(x){x.help.forEach(function(h){if(neg.has(norm(h)))improve[h]=(improve[h]||0)+1})});var improveTop=Object.keys(improve).sort(function(a,b){return improve[b]-improve[a]})[0]||'—';$('protocolKpis').innerHTML=k('Não resolvidos',fmt(un.length),pct(un.length,p.length)+'% dos atendimentos')+k('IA com mais ocorrências',top,fmt(most[top]||0)+' protocolos')+k('Com nota baixa',fmt(low.length),'de '+fmt(data.r74.filter(function(x){return x.note}).length)+' pesquisas com nota')+k('Ponto a melhorar',improveTop,fmt(improve[improveTop]||0)+' protocolo'+((improve[improveTop]||0)===1?'':'s'));var lb=listBase();$('unresolvedBadge').textContent=fmt(lb.length)+' protocolo'+(lb.length===1?'':'s');var ags=Array.from(new Set(lb.map(function(x){return x.agent}).concat(uv.agent?[uv.agent]:[]))).sort();$('unresolvedAgent').innerHTML='<option value="">Todas as IAs</option>'+ags.map(function(a){return'<option'+(a===uv.agent?' selected':'')+'>'+esc(a)+'</option>'}).join('');$('unresolvedChips').innerHTML=[['all','Todos'],['note','Com nota'],['comment','Com comentário'],['nohelp','IA não ajudou']].map(function(x){return'<button class="chip '+(uv.filter===x[0]?'active':'')+'" data-ufilter="'+x[0]+'">'+x[1]+'</button>'}).join('');renderUnList()}
function renderUnList(){var all=unresolved(),pages=Math.max(1,Math.ceil(all.length/uv.size));uv.page=Math.min(uv.page,pages);var rows=all.slice((uv.page-1)*uv.size,uv.page*uv.size);$('unresolvedList').innerHTML=rows.map(function(x){var o=uv.outcome||'nao',fp=failurePoint(x),un=isUnresolvedProtocol(x),label=o==='nao'||(o!=='falha'&&un&&x.outcome==='nao')?OUTCOME_ONE.nao:o==='falha'?'Falha de conhecimento':OUTCOME_ONE[x.outcome]||'Sem desfecho',tone=label===OUTCOME_ONE.nao||o==='falha'?'bad':'o-'+x.outcome,point=o==='sem'?'Trilha: '+trail(x):o==='nao'?(x.unresolvedPoint||x.finalPoint):o==='falha'&&fp?fp.point:x.finalPoint,extra=o==='falha'?'<span class="pill o-'+esc(x.outcome)+'">Terminou: '+esc(OUTCOME_ONE[x.outcome]||'Sem desfecho')+'</span>':'';return'<article class="protocol-card"><div class="protocol-card-head"><div class="score-box">'+(x.survey&&x.survey.note?x.survey.note:'—')+'<small>nota</small></div><div class="protocol-card-info"><div class="row-top"><b>Protocolo '+esc(x.protocol)+'</b><span class="pill">'+esc(x.agent)+'</span><span class="row-date">'+esc(x.lastDate)+'</span></div><div class="protocol-point"><span class="pill '+tone+'">'+esc(label)+'</span>'+extra+'<div>'+esc(point||label)+'</div></div></div></div><div class="protocol-card-survey">'+(x.survey&&x.survey.help.length?'<div class="protocol-detail"><strong>Como a IA ajudou</strong><div class="detail-values">'+x.survey.help.map(function(h){return'<span class="pill bad">'+esc(h)+'</span>'}).join(' ')+'</div></div>':'')+(x.survey&&x.survey.comment?'<div class="protocol-detail"><strong>Comentário</strong><div class="detail-text">'+esc(x.survey.comment)+'</div></div>':'')+'</div><div class="protocol-card-actions"><button type="button" class="view-btn" data-protocol="'+esc(x.protocol)+'">⌕ &nbsp;Ver conversa</button></div></article>'}).join('')||'<div class="empty">Nenhum protocolo encontrado com esses filtros.</div>';$('unresolvedPager').innerHTML=pages>1?'<button data-up="-1">Anterior</button><span>Página '+uv.page+' de '+pages+'</span><button data-up="1">Próxima</button>':''}
function renderQuality(){var p=data.r72.protocols.filter(function(x){return x.contact}),by={};p.forEach(function(x){var c=String(x.contact).replace(/\D/g,'').slice(-11)||norm(x.contact);if(c)(by[c]||(by[c]=[])).push(x)});var rec=[];Object.keys(by).forEach(function(key){var a=by[key].sort(function(x,y){return dt(x.firstDate)-dt(y.firstDate)});for(var i=1;i<a.length;i++){var h=(dt(a[i].firstDate)-dt(a[i-1].firstDate))/36e5;if(h>=0&&h<=24)rec.push({prev:a[i-1],next:a[i],h:h})}});$('qualityKpis').innerHTML=k('Recontatos em 24h',fmt(rec.length),'clientes que voltaram')+k('Após inatividade',fmt(rec.filter(function(x){return x.prev.outcome==='inatividade'}).length),'voltaram depois de parar')+k('Após não resolvido',fmt(rec.filter(function(x){return x.prev.outcome==='nao'}).length),'voltaram sem solução')+k('Após possível solução',fmt(rec.filter(function(x){return x.prev.outcome==='possivel'}).length),'solução não se confirmou');$('recontactBadge').textContent=fmt(rec.length)+' recontatos';$('tabQuality').textContent=rec.length||'';var mx=Math.max(1,rec.length);$('recontactWindows').innerHTML=[['≤1h',function(x){return x<=1}],['1–6h',function(x){return x>1&&x<=6}],['6–24h',function(x){return x>6}]].map(function(b){var q=rec.filter(function(x){return b[1](x.h)}).length;return'<div><i style="height:'+Math.max(4,q/mx*120)+'px"></i><b>'+q+'</b><small>'+b[0]+'</small></div>'}).join('');$('recontactList').innerHTML=rec.slice(0,50).map(function(x){return'<div class="item"><b>'+esc(x.next.protocol)+'</b><span class="pill">'+x.h.toFixed(1).replace('.',',')+'h depois</span><div class="meta">Anterior: '+esc(x.prev.protocol)+' · '+esc(x.next.agent)+' · '+esc(x.next.contact)+'</div></div>'}).join('')||'<div class="empty">Sem dados de contato suficientes para identificar recontatos.</div>';var cp=col(data.r72.rows[0]||{},['pontos de bot','bot point','ponto de bot']),counts={};data.r72.rows.forEach(function(r){var v=norm(r[cp]);if(v)counts[v]=(counts[v]||0)+1});$('checkpointList').innerHTML=bot.map(function(x){var q=counts[norm(x[0])]||0;return'<div class="checkpoint"><b>'+esc(x[0])+'</b><strong>'+q+'</strong><small>'+esc(x[1])+' · '+(q?'registrado':'zerado')+'</small></div>'}).join('')}
function renderAll(){data.r72.protocols.forEach(function(x){x.survey=data.r74.find(function(s){return s.protocol===x.protocol})||null});renderOverview();renderSurveys();renderQuality();renderProtocols();$('tabSurveys').textContent=data.r74.length||'';$('tabProtocols').textContent=unresolvedBase().length||''}
function show(v){document.querySelectorAll('[data-panel]').forEach(function(s){s.hidden=s.dataset.panel!==v});document.querySelectorAll('.tabs button').forEach(function(b){b.classList.toggle('active',b.dataset.view===v)})}
function setAuthUI(ok){
  $('loginView').hidden=ok;
  document.querySelector('.topbar').hidden=!ok;
  document.querySelector('.rail').hidden=!ok;
  $('main').hidden=!ok;
}
function showLoginError(message){
  $('loginError').textContent=message||'Não foi possível entrar.';
  $('loginError').hidden=false;
}
async function bootAuth(){
  setAuthUI(false);
  try{
    var r=await fetch('/api/auth',{cache:'no-store'});
    if(r.ok){
      setAuthUI(true);
      load();
      return;
    }
  }catch(_){}
  $('loginEmail').focus();
}
$('loginForm').onsubmit=async function(e){
  e.preventDefault();
  $('loginError').hidden=true;
  var btn=$('loginBtn'),old=btn.textContent;
  btn.disabled=true;btn.textContent='Entrando…';
  try{
    var r=await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:$('loginEmail').value})});
    var raw=await r.text(),j;
    try{j=JSON.parse(raw)}catch(_){throw new Error('Servidor respondeu de forma inválida.')}
    if(!r.ok||!j.ok)throw new Error(j.error||'E-mail não autorizado.');
    setAuthUI(true);
    await load();
  }catch(e){
    showLoginError(e.message||'Não foi possível entrar.');
  }finally{
    btn.disabled=false;btn.textContent=old;
  }
};
async function load(){var old=$('refresh').textContent;$('refresh').disabled=true;$('refresh').textContent='Consultando…';$('status').textContent='Consultando Orpen…';try{var r=await fetch('/api/reports',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({start:$('start').value,end:$('end').value})}),raw=await r.text(),j;try{j=JSON.parse(raw)}catch(_){throw new Error('Servidor respondeu '+r.status+' em vez de JSON: '+raw.slice(0,220))}if(r.status===401){setAuthUI(false);showLoginError('Sessão expirada. Informe o e-mail novamente.');throw new Error('Sessão expirada.')}if(!r.ok||!j.ok)throw new Error(j.error||'Falha ao consultar o Orpen');data={r72:analyze72(j.r72),r74:analyze74(j.r74)};renderAll();$('status').textContent='Atualizado '+new Date().toLocaleTimeString('pt-BR');$('notice').hidden=true}catch(e){$('status').textContent='Erro na coleta';$('notice').hidden=false;$('notice').textContent=e.message||'Erro ao consultar o Orpen';console.error(e)}finally{$('refresh').disabled=false;$('refresh').textContent=old}}
var se=dates('today');$('start').value=se[0];$('end').value=se[1];$('start').disabled=true;$('end').disabled=true;$('preset').onchange=function(){var c=$('preset').value==='custom';$('start').disabled=!c;$('end').disabled=!c;if(!c){var x=dates($('preset').value);$('start').value=x[0];$('end').value=x[1]}};$('refresh').onclick=load;document.querySelectorAll('.tabs button').forEach(function(b){b.onclick=function(){show(b.dataset.view)}});document.querySelectorAll('.mode').forEach(function(b){b.onclick=function(){mode=b.dataset.mode;document.querySelectorAll('.mode').forEach(function(x){x.classList.toggle('active',x===b)});renderAgents()}});$('surveySearch').oninput=function(e){sv.q=e.target.value;sv.page=1;renderSurveyList()};$('surveyAgent').onchange=function(e){sv.agent=e.target.value;sv.page=1;renderSurveyList()};$('surveyOption').onchange=function(e){sv.option=e.target.value;sv.page=1;renderSurveyList()};$('surveySize').onchange=function(e){sv.size=+e.target.value;sv.page=1;renderSurveyList()};$('unresolvedSearch').oninput=function(e){uv.q=e.target.value;uv.page=1;renderUnList()};$('unresolvedAgent').onchange=function(e){uv.agent=e.target.value;uv.page=1;renderUnList()};$('unresolvedSize').onchange=function(e){uv.size=+e.target.value;uv.page=1;renderUnList()};document.addEventListener('click',function(e){var a=e.target.closest('[data-sfilter]');if(a){sv.filter=a.dataset.sfilter;sv.page=1;renderSurveyList()}var b=e.target.closest('[data-ufilter]');if(b){uv.filter=b.dataset.ufilter;uv.page=1;renderProtocols()}var sp=e.target.closest('[data-sp]');if(sp){sv.page+=+sp.dataset.sp;renderSurveyList()}var up=e.target.closest('[data-up]');if(up){uv.page+=+up.dataset.up;renderUnList()}});show('overview');bootAuth();